### ISSUE TITLE
Travis builds sometimes fail because of java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by gijskant** [thehyve/podium#302]
E.g., in https://travis-ci.org/github/thehyve/podium/jobs/768079725#L5495:
```
2021-04-23 09:30:15.403  INFO 6420 --- [           main] n.t.p.s.RequestReviewProcessService      : New process instance started: 12086
2021-04-23 09:30:19.328  INFO 6420 --- [askExecutor-481] n.t.p.event.StatusUpdateEventListener    : Status of request f02f831c-a197-4b42-92f3-655179a0436e has been updated: Draft --> Validation
2021-04-23 09:31:46.576  WARN 6420 --- [l-4 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-4 - Thread starvation or clock leap detected (housekeeper delta=46s36ms839µs950ns).
2021-04-23 09:31:47.122  WARN 6420 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=1m310ms258µs658ns).
2021-04-23 09:31:47.122  WARN 6420 --- [l-3 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-3 - Thread starvation or clock leap detected (housekeeper delta=1m834ms668µs523ns).
2021-04-23 09:31:47.643  WARN 6420 --- [l-2 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=1m1s355ms330µs662ns).
2021-04-23 09:32:01.778  WARN 6420 --- [onMonitorThread] c.h.s.i.o.impl.InvocationMonitor         : [172.17.0.1]:5701 [dev] [3.7.8] MonitorInvocationsTask delayed 30851 ms
2021-04-23 09:32:01.778  WARN 6420 --- [onMonitorThread] c.h.s.i.o.impl.InvocationMonitor         : [172.17.0.1]:5701 [dev] [3.7.8] MonitorInvocationsTask delayed 44724 ms
2021-04-23 09:32:01.781  WARN 6420 --- [onMonitorThread] c.h.s.i.o.impl.InvocationMonitor         : [172.17.0.1]:5701 [dev] [3.7.8] BroadcastOperationHeartbeatsTask delayed 62578 ms
2021-04-23 09:32:43.422  WARN 6420 --- [onMonitorThread] c.h.s.i.o.impl.InvocationMonitor         : [172.17.0.1]:5701 [dev] [3.7.8] MonitorInvocationsTask delayed 40641 ms
2021-04-23 09:32:43.422  WARN 6420 --- [onMonitorThread] c.h.s.i.o.impl.InvocationMonitor         : [172.17.0.1]:5701 [dev] [3.7.8] BroadcastOperationHeartbeatsTask delayed 26641 ms
2021-04-23 09:32:44.032  WARN 6420 --- [cached.thread-4] com.hazelcast.instance.Node              : [172.17.0.1]:5701 [dev] [3.7.8] Terminating forcefully...
2021-04-23 09:32:44.581  WARN 6420 --- [l-4 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-4 - Thread starvation or clock leap detected (housekeeper delta=46s421ms882µs459ns).
2021-04-23 09:32:44.582  WARN 6420 --- [l-2 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Thread starvation or clock leap detected (housekeeper delta=45s355ms124µs693ns).
2021-04-23 09:32:44.582  WARN 6420 --- [l-3 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-3 - Thread starvation or clock leap detected (housekeeper delta=45s875ms793µs362ns).
2021-04-23 09:32:44.582  WARN 6420 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=45s875ms718µs678ns).
2021-04-23 09:32:45.711 ERROR 6420 --- [uire-timer-jobs] o.f.e.i.a.AcquireTimerJobsRunnable       : exception during timer job acquisition: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.ibatis.session.Configuration.newExecutor(Configuration.java:548)
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSessionFromDataSource(DefaultSqlSessionFactory.java:96)
	at org.apache.ibatis.session.defaults.DefaultSqlSessionFactory.openSession(DefaultSqlSessionFactory.java:47)
	at org.flowable.engine.impl.db.DbSqlSession.<init>(DbSqlSession.java:159)
	at org.flowable.engine.impl.db.DbSqlSessionFactory.openSession(DbSqlSessionFactory.java:75)
	at org.flowable.engine.common.impl.interceptor.AbstractCommandContext.getSession(AbstractCommandContext.java:225)
	at org.flowable.engine.impl.persistence.AbstractManager.getSession(AbstractManager.java:68)
	at org.flowable.engine.impl.persistence.entity.data.AbstractDataManager.getDbSqlSession(AbstractDataManager.java:47)
	at org.flowable.engine.impl.persistence.entity.data.impl.MybatisTimerJobDataManager.findTimerJobsToExecute(MybatisTimerJobDataManager.java:69)
	at org.flowable.engine.impl.persistence.entity.TimerJobEntityManagerImpl.findTimerJobsToExecute(TimerJobEntityManagerImpl.java:70)
	at org.flowable.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:40)
	at org.flowable.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:29)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:39)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:80)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:59)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:44)
	at org.flowable.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:51)
	at org.flowable.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:64)
	at org.flowable.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.asyncexecutor.AcquireTimerJobsRunnable.run(AcquireTimerJobsRunnable.java:57)
	at java.lang.Thread.run(Thread.java:748)
2021-04-23 09:32:45.712 ERROR 6420 --- [uire-async-jobs] o.f.e.i.a.AcquireAsyncJobsDueRunnable    : exception during async job acquisition: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
2021-04-23 09:32:45.714 ERROR 6420 --- [et-expired-jobs] o.f.e.i.a.ResetExpiredJobsRunnable       : exception during resetting expired jobs: Could not open JPA EntityManager for transaction; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.asyncexecutor.ResetExpiredJobsRunnable.run(ResetExpiredJobsRunnable.java:57)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
2021-04-23 09:32:45.715 ERROR 6420 --- [uire-timer-jobs] o.f.e.i.a.AcquireTimerJobsRunnable       : exception during timer job acquisition: Could not open JPA EntityManager for transaction; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:431)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:377)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.asyncexecutor.AcquireTimerJobsRunnable.run(AcquireTimerJobsRunnable.java:57)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
2021-04-23 09:32:45.715 ERROR 6420 --- [uire-timer-jobs] o.f.e.i.a.AcquireTimerJobsRunnable       : exception during timer job acquisition: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.apache.ibatis.reflection.MetaObject.getValue(MetaObject.java:113)
	at org.apache.ibatis.executor.BaseExecutor.createCacheKey(BaseExecutor.java:219)
	at org.apache.ibatis.executor.CachingExecutor.createCacheKey(CachingExecutor.java:146)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:82)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.flowable.engine.impl.db.DbSqlSession.selectListWithRawParameter(DbSqlSession.java:313)
	at org.flowable.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:298)
	at org.flowable.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:288)
	at org.flowable.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:253)
	at org.flowable.engine.impl.db.DbSqlSession.selectList(DbSqlSession.java:247)
	at org.flowable.engine.impl.persistence.entity.data.impl.MybatisTimerJobDataManager.findTimerJobsToExecute(MybatisTimerJobDataManager.java:69)
	at org.flowable.engine.impl.persistence.entity.TimerJobEntityManagerImpl.findTimerJobsToExecute(TimerJobEntityManagerImpl.java:70)
	at org.flowable.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:40)
	at org.flowable.engine.impl.cmd.AcquireTimerJobsCmd.execute(AcquireTimerJobsCmd.java:29)
	at org.flowable.engine.impl.interceptor.CommandInvoker$1.run(CommandInvoker.java:39)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperation(CommandInvoker.java:80)
	at org.flowable.engine.impl.interceptor.CommandInvoker.executeOperations(CommandInvoker.java:59)
	at org.flowable.engine.impl.interceptor.CommandInvoker.execute(CommandInvoker.java:44)
	at org.flowable.engine.impl.interceptor.TransactionContextInterceptor.execute(TransactionContextInterceptor.java:51)
	at org.flowable.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:64)
	at org.flowable.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:47)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at org.flowable.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:45)
	at org.flowable.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:56)
	at org.flowable.engine.impl.cfg.CommandExecutorImpl.execute(CommandExecutorImpl.java:51)
	at org.flowable.engine.impl.asyncexecutor.AcquireTimerJobsRunnable.run(AcquireTimerJobsRunnable.java:57)
	at java.lang.Thread.run(Thread.java:748)
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

**Comment by gijskant** [comment]
Did not experience this problem the last couple of weeks, closing the issue.
